## Лабораторная работа по курсу «Основы Python»

### При выполнении работы допускается использование любых внешних модулей и пакетов.

#### Задача 1

Дан список:

In [ ]:
list_01 = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 14, 46, 273, 22, 99, 15, 1000]

Напишите алгоритм, который выводит число, равное сумме элементов списка, которые больше 10, но меньше 100, и которые больше 200, но меньше 500.

In [4]:
list_01 = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 14, 46, 273, 22, 99, 15, 1000]

sum_ = 0

for num in list_01:
    if 10 < num < 100 or 200 < num < 500:
        sum_ += num

print(sum_)

1291

#### Задача 2

Дана строка:

In [ ]:
some_string = "History is always written by the winners. When two cultures clash, the loser is obliterated, and the winner writes the history books - books which glorify their own cause and disparage the conquered foe. As Napoleon once said, 'What is history, but a fable agreed upon?'"

Напишите функцию, которая будет принимать в качестве аргумента букву и выводить все слова из строки, начинающиеся на эту букву (например, “w”).

In [9]:
def find_words_starting_with_letter(string, letter):
    """
    Функция выводит все слова из строки, которые начинаются с указанной буквы.

    Аргументы:
    - string (str): Исходная строка.
    - letter (str): Буква, по которой необходимо фильтровать слова.

    Возвращает:
    - None (функция просто выводит найденные слова).

    """
    words = string.split()  # Разбиение строки на список слов

    for word in words:
        clean_word = ''.join(filter(str.isalpha, word))  # Удаление неалфавитных символов в начале слова
        if clean_word.lower().startswith(letter.lower()):  # Проверка, начинается ли слово с указанной буквы
            print(clean_word)


some_string = "History is always written by the winners. When two cultures clash, the loser is obliterated, and the winner writes the history books - books which glorify their own cause and disparage the conquered foe. As Napoleon once said, 'What is history, but a fable agreed upon?'"

letter = 'w'

find_words_starting_with_letter(some_string, letter)

written
winners
When
winner
writes
which
What

#### Задача 3

Напишите функцию, которая генерирует случайную последовательность из 6 цифр, причем в этой последовательности должна быть как минимум одна цифра 3. Позиция 3 определяться случайным образом. Например: "456379" или "033456".

In [16]:
import random

def generate_sequence():
    """
    Функция генерирует случайную последовательность из 6 цифр, включая минимум одну цифру 3.

    Возвращает:
    - sequence (str): Сгенерированная последовательность.

    """
    sequence = ''.join(random.choice('0123456789') for _ in range(5))  # Генерация последовательности из 5 случайных цифр
    position = random.randint(0, 5)  # Случайная позиция для вставки цифры 3
    sequence = sequence[:position] + '3' + sequence[position:]  # Вставка цифры 3 на случайную позицию

    return sequence


generated_sequence = generate_sequence()
print(generated_sequence)

138617

#### Задача 4

Данные студентов представлены в виде списка списков:

In [ ]:
students = [
["0001", "Антонов", "Антон", "Игоревич", "20.08.2009","БСТ161"],
["1102", "Богов", "Артем", "Игоревич", "25.01.2010","БСТ162"],
["0333", "Глаголева", "Анастасия", "Николаевна", "11.07.2009", "БСТ163"],
["4004", "Степанова", "Наталья", "Александровна", "13.02.2008", "БСТ161"],
["0045", "Боков", "Игорь", "Харитонович", "02.06.2009", "БСТ161"],
["0096", "Васильков", "Валентин", "Сергеевич", "20.03.2009", "БСТ164"],
["0607", "Сиропова", "Виолетта", "Эдуардовна", "28.05.2010", "БСТ162"],
["4014", "Потапов", "Дмитрий", "Станиславович", "14.02.2012", "БСТ161"]
    ]

1. Преобразуйте данные таким образом, чтобы они были представлены в виде словаря, в котором ключами являются номера студентов, а значениями — список из других данных о студентах.

2. Напишите функцию, которая принимает номер группы и выводит пронумерованный и упорядоченный по алфавиту список (фамилии, имена, отчества) всех студентов этой группы. Необходимо обращаться к словарю.

In [17]:
students = [
    ["0001", "Антонов", "Антон", "Игоревич", "20.08.2009", "БСТ161"],
    ["1102", "Богов", "Артем", "Игоревич", "25.01.2010", "БСТ162"],
    ["0333", "Глаголева", "Анастасия", "Николаевна", "11.07.2009", "БСТ163"],
    ["4004", "Степанова", "Наталья", "Александровна", "13.02.2008", "БСТ161"],
    ["0045", "Боков", "Игорь", "Харитонович", "02.06.2009", "БСТ161"],
    ["0096", "Васильков", "Валентин", "Сергеевич", "20.03.2009", "БСТ164"],
    ["0607", "Сиропова", "Виолетта", "Эдуардовна", "28.05.2010", "БСТ162"],
    ["4014", "Потапов", "Дмитрий", "Станиславович", "14.02.2012", "БСТ161"]
]

def convert_students_to_dict(students):
    """
    Функция преобразует список студентов в словарь.

    Аргументы:
    - students (list): Список студентов, где каждый элемент - список данных о студенте.

    Возвращает:
    - students_dict (dict): Словарь студентов, где ключи - номера студентов, а значения - список данных о студентах.

    """
    students_dict = {}

    for student in students:
        student_id = student[0]
        student_data = student[1:]
        students_dict[student_id] = student_data

    return students_dict


def print_group_students(group):
    """
    Функция выводит список (фамилии, имена, отчества) всех студентов заданной группы, отсортированный по алфавиту.

    Аргументы:
    - group (str): Номер группы студентов.

    Возвращает:
    - None (функция просто выводит список студентов).

    """
    students_dict = convert_students_to_dict(students)

    group_students = []
    for student_id, student_data in students_dict.items():
        if student_data[-1] == group:
            group_students.append(student_data[:3])

    group_students.sort()  # Сортировка списка студентов по алфавиту

    for idx, student in enumerate(group_students, 1):
        print(f"{idx}. {' '.join(student)}")


group_number = "БСТ161"
print_group_students(group_number)

1. Антонов Антон Игоревич
2. Боков Игорь Харитонович
3. Потапов Дмитрий Станиславович
4. Степанова Наталья Александровна

#### Задача 5

Создайте класс Student, который создает объекты с данными о студентах (как в задаче 4). Класс должен иметь следующие методы: add_to_dict (добавляет объект в словарь из задачи 4), update_dict (обновляет запись о студенте в словаре из задачи 4), change_group (изменяет номер группы студента), change_id (изменяет номер студента) и print_date (выводит на экран данные студента).

In [19]:
class Student:
    def __init__(self, s_id, last_name, first_name, patronomic_name, date, group):
        self.student_id = s_id
        self.last_name = last_name
        self.first_name = first_name
        self.patronomic_name = patronomic_name
        self.date = date
        self.group = group

    def add_to_dict(self, students_dict):
        """
        Метод добавляет объект Student в словарь студентов.

        Аргументы:
        - students_dict (dict): Словарь студентов.

        Возвращает:
        - None

        """
        students_dict[self.student_id] = [self.last_name, self.first_name, self.patronomic_name, self.date, self.group]

    def update_dict(self, students_dict):
        """
        Метод обновляет запись о студенте в словаре, используя текущие значения атрибутов объекта.

        Аргументы:
        - students_dict (dict): Словарь студентов.

        Возвращает:
        - None

        """
        if self.student_id in students_dict:
            students_dict[self.student_id] = [self.last_name, self.first_name, self.patronomic_name, self.date, self.group]

    def change_group(self, new_group):
        """
        Метод изменяет номер группы студента.

        Аргументы:
        - new_group (str): Новый номер группы.

        Возвращает:
        - None

        """
        self.group = new_group

    def change_id(self, new_id):
        """
        Метод изменяет номер студента.

        Аргументы:
        - new_id (str): Новый номер студента.

        Возвращает:
        - None

        """
        self.student_id = new_id

    def print_data(self):
        """
        Метод выводит данные студента на экран.

        Возвращает:
        - None

        """
        print(f"Student ID: {self.student_id}")
        print(f"Last Name: {self.last_name}")
        print(f"First Name: {self.first_name}")
        print(f"Patronomic Name: {self.patronomic_name}")
        print(f"Date: {self.date}")
        print(f"Group: {self.group}")

1. Создайте объект класса, добавьте его в словарь. Обновленный словарь выведете на экран.

In [ ]:
volkova = Student('0001', 'Волкова', 'Галина', 'Сергеевна', '18.12.2022', 'БСТ100')

In [20]:
students_dict = {}

volkova = Student('0001', 'Волкова', 'Галина', 'Сергеевна', '18.12.2022', 'БСТ100')
volkova.add_to_dict(students_dict)

# Вывод обновленного словаря на экран
for student_id, student_data in students_dict.items():
    print(f"Student ID: {student_id}")
    print(f"Last Name: {student_data[0]}")
    print(f"First Name: {student_data[1]}")
    print(f"Patronomic Name: {student_data[2]}")
    print(f"Date: {student_data[3]}")
    print(f"Group: {student_data[4]}")
    print("---")

Student ID: 0001
Last Name: Волкова
First Name: Галина
Patronomic Name: Сергеевна
Date: 18.12.2022
Group: БСТ100
---

2. Измените номер группы студентки Волковой на 'БСТ161' и выведите обновленный список группы.

In [21]:
students_dict = {}

volkova = Student('0001', 'Волкова', 'Галина', 'Сергеевна', '18.12.2022', 'БСТ100')
volkova.add_to_dict(students_dict)

volkova.change_group('БСТ161')
volkova.update_dict(students_dict)

# Вывод обновленного списка студентов группы БСТ161
for student_id, student_data in students_dict.items():
    if student_data[4] == 'БСТ161':
        print(f"Student ID: {student_id}")
        print(f"Last Name: {student_data[0]}")
        print(f"First Name: {student_data[1]}")
        print(f"Patronomic Name: {student_data[2]}")
        print(f"Date: {student_data[3]}")
        print(f"Group: {student_data[4]}")
        print("---")

Student ID: 0001
Last Name: Волкова
First Name: Галина
Patronomic Name: Сергеевна
Date: 18.12.2022
Group: БСТ161
---

#### Задача 6

Дана матрица matrix. Напишите код, который будет транспонировать её (то есть, делать из строк столбцы) в maytix_t:

matrix_t = [
    [0, 6, 3, 4, 5],
    [1, 2, 3, 6, 7],
    [2, 2, 3, 7, 3],
    [4, 1, 3, 1, 4],
    [8, 9, 3, 2, 0]
]

In [22]:
matrix = [
    [0,1,2,4,8],
    [6,2,2,1,9],
    [3,3,3,3,3],
    [4,6,7,1,2],
    [5,7,3,4,0]
]

rows = len(matrix)
cols = len(matrix[0])

# Создаем пустую транспонированную матрицу matrix_t
matrix_t = [[0 for _ in range(rows)] for _ in range(cols)]

# Транспонируем матрицу
for i in range(rows):
    for j in range(cols):
        matrix_t[j][i] = matrix[i][j]

# Выводим транспонированную матрицу matrix_t на экран
for row in matrix_t:
    print(row)

[0, 6, 3, 4, 5]
[1, 2, 3, 6, 7]
[2, 2, 3, 7, 3]
[4, 1, 3, 1, 4]
[8, 9, 3, 2, 0]